<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class LeaveMessageMailable extends Mailable
{
    use Queueable, SerializesModels;

    public string $sender; // Property to hold the frontend reset URL
    public string $email;
    public string $message;

    /**
     * Create a new message instance.
     *
     * @param string $resetToken The password reset token generated by Laravel
     * @param string $userEmail The email of the user requesting the reset
     * @param string $userName (Optional) The user's name, if available
     * @return void
     */
    public function __construct(string $sender, string $email, string $message)
    {
        $this->sender = $sender;
        $this->email = $email;
        $this->message = $message;
    }

    /**
     * Get the message envelope.
     */
    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Message from ' . $this->sender . ' - ' . config('app.name'), // Dynamic subject
        );
    }

    /**
     * Get the message content definition.
     */
    public function content(): Content
    {
        return new Content(
            // markdown: 'emails.password-reset', // Use a Blade Markdown view
            view: 'emails.custom-leave-message',
            with: [
                'sender' => $this->sender,
                'email' => $this->email,
                'userMessage' => $this->message,
            ]
        );
    }

    /**
     * Get the attachments for the message.
     *
     * @return array<int, \Illuminate\Mail\Mailables\Attachment>
     */
    public function attachments(): array
    {
        return [];
    }
}
