<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;
use App\Models\User;

class VerifyEmailMailable extends Mailable
{
    use Queueable, SerializesModels;

    public string $verificationUrl; // Property to hold the frontend reset URL
    public string $userName; // Optional: To personalize the email (e.g., "Hello, [User Name]")

    /**
     * Create a new message instance.
     *
     * @param string $resetToken The password reset token generated by Laravel
     * @param string $userEmail The email of the user requesting the reset
     * @param string $userName (Optional) The user's name, if available
     * @return void
     */
    public function __construct(User $user)
    {
        // Construct the frontend reset URL
        // Ensure config('app.frontend_url') is set in .env and config/app.php
        $this->verificationUrl = config('app.frontend_url') . '/verify?token=' . $user->email_verification_token . '&email=' . urlencode($user->email);
        $this->userName = $user->username ?? 'User'; // Default to 'User' if name is not provider

    }

    /**
     * Get the message envelope.
     */
    public function envelope(): Envelope
    {
        return new Envelope(
            subject: 'Vefify your account - ' . config('app.name'), // Dynamic subject
        );
    }

    /**
     * Get the message content definition.
     */
    public function content(): Content
    {
        return new Content(
            // markdown: 'emails.password-reset', // Use a Blade Markdown view
            view: 'emails.custom-verify-email',
            with: [
                'verificationUrl' => $this->verificationUrl,
                'userName' => $this->userName,
                // 'expireMinutes' => $this->expireMinutes,
            ]
        );
    }

    /**
     * Get the attachments for the message.
     *
     * @return array<int, \Illuminate\Mail\Mailables\Attachment>
     */
    public function attachments(): array
    {
        return [];
    }
}
